# Generated by Django 5.2.4 on 2025-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
