# Generated by Django 5.2.4 on 2025-07-03 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_remove_carouselimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
