# Generated by Django 5.2.4 on 2025-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_carouselimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
